# Generated by Django 5.0.6 on 2025-10-31 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='api.project')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='uploaded_fi_project_2276a3_idx')],
            },
        ),
    ]
