# Generated by Django 5.0.6 on 2025-10-31 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_json', models.JSONField()),
                ('num_rows', models.IntegerField()),
                ('sample_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tables', to='api.project')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tables', to='api.uploadedfile')),
            ],
            options={
                'db_table': 'data_tables',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='data_tables_project_c8cafb_idx')],
            },
        ),
    ]
