# Generated by Django 5.0.6 on 2025-10-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='edited_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='full_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='datatable',
            index=models.Index(fields=['updated_at'], name='data_tables_updated_a27cfe_idx'),
        ),
    ]
