# Generated by Django 5.0.6 on 2025-10-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_datatable_edited_data_json_datatable_full_data_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('area', 'Area'), ('pie', 'Pie'), ('scatter', 'Scatter')], default='bar', max_length=20)),
                ('selected_columns_json', models.JSONField(default=dict, help_text='Column selection: {x: str, y: [str], groupBy?: str, label?: str}')),
                ('style_json', models.JSONField(blank=True, default=dict, help_text='Styling options: title, colors, legend position, axes labels, etc.', null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_config', to='api.project')),
            ],
            options={
                'db_table': 'chart_configs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project'], name='chart_confi_project_ab9a73_idx'), models.Index(fields=['updated_at'], name='chart_confi_updated_472ce2_idx')],
            },
        ),
    ]
