# Generated by Django 5.0.6 on 2025-10-31 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chartconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('result_storage_key', models.CharField(blank=True, help_text='Storage path/key for the generated PDF file', max_length=500, null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if export failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='api.project')),
            ],
            options={
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='export_jobs_project_1c7107_idx'), models.Index(fields=['status'], name='export_jobs_status_f80fd4_idx')],
            },
        ),
    ]
